var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(c,b,e){if(e.get||e.set)throw new TypeError("ES3 does not support getters and setters.");c!=Array.prototype&&c!=Object.prototype&&(c[b]=e.value)};$jscomp.getGlobal=function(c){return"undefined"!=typeof window&&window===c?c:"undefined"!=typeof global&&null!=global?global:c};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(c,b,e,d){if(b){e=$jscomp.global;c=c.split(".");for(d=0;d<c.length-1;d++){var f=c[d];f in e||(e[f]={});e=e[f]}c=c[c.length-1];d=e[c];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(e,c,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Number.isNaN",function(c){return c?c:function(b){return"number"===typeof b&&isNaN(b)}},"es6-impl","es3");
$jscomp.polyfill("Number.isFinite",function(c){return c?c:function(b){return"number"!==typeof b?!1:!isNaN(b)&&Infinity!==b&&-Infinity!==b}},"es6-impl","es3");$jscomp.polyfill("Number.isInteger",function(c){return c?c:function(b){return Number.isFinite(b)?b===Math.floor(b):!1}},"es6-impl","es3");function get_pixel(c,b,e){return e.getContext("2d").getImageData(c,b,1,1).data}
function set_pixel(c,b,e,d,f,a,h){var g=e.getContext("2d"),l=g.getImageData(0,0,e.width,e.height),m=l.data;c=4*(c+b*e.width);m[c]=d;m[c+1]=f;m[c+2]=a;m[c+3]=h;g.putImageData(l,0,0)};function menu_function(){0<image1.width&&-1==image_type1&&(image_type1=image_type(image1));0<image2.width&&-1==image_type2&&(image_type2=image_type(image2),image_type2=image_type(image2));document.getElementById("myDropdown").classList.toggle("show");document.getElementById("menu1").style.visibility="hidden";document.getElementById("menu2").style.visibility="hidden";document.getElementById("menu3").style.visibility="hidden";document.getElementById("menu4").style.visibility="hidden";document.getElementById("menu5").style.visibility=
"hidden";document.getElementById("menu6").style.visibility="hidden";document.getElementById("menu7").style.visibility="hidden";document.getElementById("menu8").style.visibility="hidden";document.getElementById("menu_options").style.visibility="hidden";document.getElementById("menu_options2").style.visibility="hidden";document.getElementById("menu_options3").style.visibility="hidden"}
function menu_function1(){document.getElementById("myDropdown1").classList.toggle("show");document.getElementById("menu2").style.visibility="hidden";document.getElementById("menu3").style.visibility="hidden";document.getElementById("menu4").style.visibility="hidden";document.getElementById("menu5").style.visibility="hidden";document.getElementById("menu6").style.visibility="hidden";document.getElementById("menu7").style.visibility="hidden";document.getElementById("menu8").style.visibility="hidden";
document.getElementById("menu_options").style.visibility="hidden";document.getElementById("menu_options2").style.visibility="hidden";document.getElementById("menu_options3").style.visibility="hidden"}
function menu_function2(){document.getElementById("myDropdown2").classList.toggle("show");document.getElementById("menu1").style.visibility="hidden";document.getElementById("menu3").style.visibility="hidden";document.getElementById("menu4").style.visibility="hidden";document.getElementById("menu5").style.visibility="hidden";document.getElementById("menu6").style.visibility="hidden";document.getElementById("menu7").style.visibility="hidden";document.getElementById("menu8").style.visibility="hidden";
document.getElementById("menu_options").style.visibility="hidden";document.getElementById("menu_options2").style.visibility="hidden";document.getElementById("menu_options3").style.visibility="hidden"}
function menu_function3(){document.getElementById("myDropdown3").classList.toggle("show");document.getElementById("menu1").style.visibility="hidden";document.getElementById("menu2").style.visibility="hidden";document.getElementById("menu4").style.visibility="hidden";document.getElementById("menu5").style.visibility="hidden";document.getElementById("menu6").style.visibility="hidden";document.getElementById("menu7").style.visibility="hidden";document.getElementById("menu8").style.visibility="hidden";
document.getElementById("menu_options").style.visibility="hidden";document.getElementById("menu_options2").style.visibility="hidden";document.getElementById("menu_options3").style.visibility="hidden"}
function menu_function4(){document.getElementById("myDropdown4").classList.toggle("show");document.getElementById("menu1").style.visibility="hidden";document.getElementById("menu2").style.visibility="hidden";document.getElementById("menu3").style.visibility="hidden";document.getElementById("menu5").style.visibility="hidden";document.getElementById("menu6").style.visibility="hidden";document.getElementById("menu7").style.visibility="hidden";document.getElementById("menu8").style.visibility="hidden";
document.getElementById("menu_options").style.visibility="hidden";document.getElementById("menu_options2").style.visibility="hidden";document.getElementById("menu_options3").style.visibility="hidden"}
function menu_function5(){document.getElementById("myDropdown5").classList.toggle("show");document.getElementById("menu1").style.visibility="hidden";document.getElementById("menu2").style.visibility="hidden";document.getElementById("menu3").style.visibility="hidden";document.getElementById("menu4").style.visibility="hidden";document.getElementById("menu6").style.visibility="hidden";document.getElementById("menu7").style.visibility="hidden";document.getElementById("menu8").style.visibility="hidden";
document.getElementById("menu_options").style.visibility="hidden";document.getElementById("menu_options2").style.visibility="hidden";document.getElementById("menu_options3").style.visibility="hidden"}
function menu_function6(){document.getElementById("myDropdown6").classList.toggle("show");document.getElementById("menu1").style.visibility="hidden";document.getElementById("menu2").style.visibility="hidden";document.getElementById("menu3").style.visibility="hidden";document.getElementById("menu4").style.visibility="hidden";document.getElementById("menu5").style.visibility="hidden";document.getElementById("menu7").style.visibility="hidden";document.getElementById("menu8").style.visibility="hidden";
document.getElementById("menu_options").style.visibility="hidden";document.getElementById("menu_options2").style.visibility="hidden";document.getElementById("menu_options3").style.visibility="hidden"}
function menu_function7(){document.getElementById("myDropdown7").classList.toggle("show");document.getElementById("menu1").style.visibility="hidden";document.getElementById("menu2").style.visibility="hidden";document.getElementById("menu3").style.visibility="hidden";document.getElementById("menu4").style.visibility="hidden";document.getElementById("menu5").style.visibility="hidden";document.getElementById("menu6").style.visibility="hidden";document.getElementById("menu8").style.visibility="hidden";
document.getElementById("menu_options").style.visibility="hidden";document.getElementById("menu_options2").style.visibility="hidden";document.getElementById("menu_options3").style.visibility="hidden"}
function menu_function8(){document.getElementById("myDropdown8").classList.toggle("show");document.getElementById("menu1").style.visibility="hidden";document.getElementById("menu2").style.visibility="hidden";document.getElementById("menu3").style.visibility="hidden";document.getElementById("menu4").style.visibility="hidden";document.getElementById("menu5").style.visibility="hidden";document.getElementById("menu6").style.visibility="hidden";document.getElementById("menu7").style.visibility="hidden";
document.getElementById("menu_options").style.visibility="hidden";document.getElementById("menu_options2").style.visibility="hidden";document.getElementById("menu_options3").style.visibility="hidden"}
function menu_function_options(){document.getElementById("myDropdown_options").classList.toggle("show");document.getElementById("menu1").style.visibility="hidden";document.getElementById("menu2").style.visibility="hidden";document.getElementById("menu3").style.visibility="hidden";document.getElementById("menu4").style.visibility="hidden";document.getElementById("menu5").style.visibility="hidden";document.getElementById("menu6").style.visibility="hidden";document.getElementById("menu7").style.visibility=
"hidden";document.getElementById("menu8").style.visibility="hidden";document.getElementById("menu_options2").style.visibility="hidden";document.getElementById("menu_options3").style.visibility="hidden"}
function menu_function_options2(){document.getElementById("myDropdown_options2").classList.toggle("show");document.getElementById("menu1").style.visibility="hidden";document.getElementById("menu2").style.visibility="hidden";document.getElementById("menu3").style.visibility="hidden";document.getElementById("menu4").style.visibility="hidden";document.getElementById("menu5").style.visibility="hidden";document.getElementById("menu6").style.visibility="hidden";document.getElementById("menu7").style.visibility=
"hidden";document.getElementById("menu8").style.visibility="hidden";document.getElementById("menu_options").style.visibility="hidden";document.getElementById("menu_options3").style.visibility="hidden"}
function menu_function_options3(){document.getElementById("myDropdown_options3").classList.toggle("show");document.getElementById("menu1").style.visibility="hidden";document.getElementById("menu2").style.visibility="hidden";document.getElementById("menu3").style.visibility="hidden";document.getElementById("menu4").style.visibility="hidden";document.getElementById("menu5").style.visibility="hidden";document.getElementById("menu6").style.visibility="hidden";document.getElementById("menu7").style.visibility=
"hidden";document.getElementById("menu8").style.visibility="hidden";document.getElementById("menu_options2").style.visibility="hidden";document.getElementById("menu_options").style.visibility="hidden"}function filter_function(){var c,b,e;c=document.getElementById("myInput").value.toUpperCase();div=document.getElementById("myDropdown");b=div.getElementsByTagName("a");for(e=0;e<b.length;e++)-1<b[e].innerHTML.toUpperCase().indexOf(c)?b[e].style.display="":b[e].style.display="none"}
function filter_function1(){var c,b,e;c=document.getElementById("myInput1").value.toUpperCase();div=document.getElementById("myDropdown1");b=div.getElementsByTagName("a");for(e=0;e<b.length;e++)-1<b[e].innerHTML.toUpperCase().indexOf(c)?b[e].style.display="":b[e].style.display="none"}
function filter_function2(){var c,b,e;c=document.getElementById("myInput2").value.toUpperCase();div=document.getElementById("myDropdown2");b=div.getElementsByTagName("a");for(e=0;e<b.length;e++)-1<b[e].innerHTML.toUpperCase().indexOf(c)?b[e].style.display="":b[e].style.display="none"}
function filter_function3(){var c,b,e;c=document.getElementById("myInput3").value.toUpperCase();div=document.getElementById("myDropdown3");b=div.getElementsByTagName("a");for(e=0;e<b.length;e++)-1<b[e].innerHTML.toUpperCase().indexOf(c)?b[e].style.display="":b[e].style.display="none"}
function filter_function4(){var c,b,e;c=document.getElementById("myInput4").value.toUpperCase();div=document.getElementById("myDropdown4");b=div.getElementsByTagName("a");for(e=0;e<b.length;e++)-1<b[e].innerHTML.toUpperCase().indexOf(c)?b[e].style.display="":b[e].style.display="none"}
function filter_function5(){var c,b,e;c=document.getElementById("myInput5").value.toUpperCase();div=document.getElementById("myDropdown5");b=div.getElementsByTagName("a");for(e=0;e<b.length;e++)-1<b[e].innerHTML.toUpperCase().indexOf(c)?b[e].style.display="":b[e].style.display="none"}
function filter_function6(){var c,b,e;c=document.getElementById("myInput6").value.toUpperCase();div=document.getElementById("myDropdown6");b=div.getElementsByTagName("a");for(e=0;e<b.length;e++)-1<b[e].innerHTML.toUpperCase().indexOf(c)?b[e].style.display="":b[e].style.display="none"}
function filter_function7(){var c,b,e;c=document.getElementById("myInput7").value.toUpperCase();div=document.getElementById("myDropdown7");b=div.getElementsByTagName("a");for(e=0;e<b.length;e++)-1<b[e].innerHTML.toUpperCase().indexOf(c)?b[e].style.display="":b[e].style.display="none"}
function filter_function8(){var c,b,e;c=document.getElementById("myInput8").value.toUpperCase();div=document.getElementById("myDropdown8");b=div.getElementsByTagName("a");for(e=0;e<b.length;e++)-1<b[e].innerHTML.toUpperCase().indexOf(c)?b[e].style.display="":b[e].style.display="none"}
function filter_function_options(){var c,b,e;c=document.getElementById("myInput_options").value.toUpperCase();div=document.getElementById("myDropdown_options");b=div.getElementsByTagName("a");for(e=0;e<b.length;e++)-1<b[e].innerHTML.toUpperCase().indexOf(c)?b[e].style.display="":b[e].style.display="none"}
function filter_function_options2(){var c,b,e;c=document.getElementById("myInput_options2").value.toUpperCase();div=document.getElementById("myDropdown_options2");b=div.getElementsByTagName("a");for(e=0;e<b.length;e++)-1<b[e].innerHTML.toUpperCase().indexOf(c)?b[e].style.display="":b[e].style.display="none"}
function filter_function_options3(){var c,b,e;c=document.getElementById("myInput_options3").value.toUpperCase();div=document.getElementById("myDropdown_options3");b=div.getElementsByTagName("a");for(e=0;e<b.length;e++)-1<b[e].innerHTML.toUpperCase().indexOf(c)?b[e].style.display="":b[e].style.display="none"}document.getElementById("menu_choose1").addEventListener("click",menu_visible_1);document.getElementById("menu_choose2").addEventListener("click",menu_visible_2);
document.getElementById("menu_choose3").addEventListener("click",menu_visible_3);document.getElementById("menu_choose4").addEventListener("click",menu_visible_4);document.getElementById("menu_choose5").addEventListener("click",menu_visible_5);document.getElementById("menu_choose6").addEventListener("click",menu_visible_6);document.getElementById("menu_choose7").addEventListener("click",menu_visible_7);document.getElementById("menu_choose8").addEventListener("click",menu_visible_8);
document.getElementById("menu_options").addEventListener("click",menu_visible_options);document.getElementById("menu_options2").addEventListener("click",menu_visible_options2);document.getElementById("menu_options3").addEventListener("click",menu_visible_options3);document.getElementById("menu_choose11").addEventListener("click",menu_visible_options);document.getElementById("menu_choose12").addEventListener("click",menu_12);document.getElementById("menu_choose13").addEventListener("click",menu_13);
document.getElementById("menu_choose14").addEventListener("click",menu_14);document.getElementById("menu_choose21").addEventListener("click",menu_visible_options);document.getElementById("menu_choose22").addEventListener("click",menu_22);document.getElementById("menu_choose23").addEventListener("click",menu_23);document.getElementById("menu_choose24").addEventListener("click",menu_24);document.getElementById("menu_choose31").addEventListener("click",menu_31);
document.getElementById("menu_choose32").addEventListener("click",menu_32);document.getElementById("menu_choose33").addEventListener("click",menu_33);document.getElementById("menu_choose41").addEventListener("click",menu_41);document.getElementById("menu_choose42").addEventListener("click",menu_42);document.getElementById("menu_choose43").addEventListener("click",menu_43);document.getElementById("menu_choose44").addEventListener("click",menu_44);
document.getElementById("menu_choose51").addEventListener("click",menu_51);document.getElementById("menu_choose52").addEventListener("click",menu_52);document.getElementById("menu_choose53").addEventListener("click",menu_53);document.getElementById("menu_choose54").addEventListener("click",menu_54);document.getElementById("menu_choose61").addEventListener("click",menu_61);document.getElementById("menu_choose62").addEventListener("click",menu_62);
document.getElementById("menu_choose71").addEventListener("click",menu_71);document.getElementById("menu_choose72").addEventListener("click",menu_72);document.getElementById("menu_choose81").addEventListener("click",menu_visible_options2);document.getElementById("menu_choose82").addEventListener("click",menu_visible_options3);document.getElementById("menu_choose83").addEventListener("click",menu_83);document.getElementById("menu_choose_o1").addEventListener("click",menu_o1);
document.getElementById("menu_choose_o2").addEventListener("click",menu_o2);document.getElementById("menu_choose_o21").addEventListener("click",menu_o21);document.getElementById("menu_choose_o22").addEventListener("click",menu_o22);document.getElementById("menu_choose_o31").addEventListener("click",menu_o31);document.getElementById("menu_choose_o32").addEventListener("click",menu_o32);
function menu_visible_1(){2!=image_type1?(alert("The first image is not gray!"),menu_function1()):(document.getElementById("menu1").style.visibility="visible",document.getElementById("menu2").style.visibility="hidden",document.getElementById("menu3").style.visibility="hidden",document.getElementById("menu4").style.visibility="hidden",document.getElementById("menu5").style.visibility="hidden",document.getElementById("menu6").style.visibility="hidden",document.getElementById("menu7").style.visibility=
"hidden",document.getElementById("menu8").style.visibility="hidden",document.getElementById("menu_options").style.visibility="hidden",document.getElementById("menu_options2").style.visibility="hidden",document.getElementById("menu_options3").style.visibility="hidden")}
function menu_visible_2(){3!=image_type1?(alert("The first image is not color!"),menu_function1()):(document.getElementById("menu2").style.visibility="visible",document.getElementById("menu2").style.position="absolute",document.getElementById("menu2").style.left="95px",document.getElementById("menu1").style.visibility="hidden",document.getElementById("menu3").style.visibility="hidden",document.getElementById("menu4").style.visibility="hidden",document.getElementById("menu5").style.visibility="hidden",
document.getElementById("menu6").style.visibility="hidden",document.getElementById("menu7").style.visibility="hidden",document.getElementById("menu8").style.visibility="hidden",document.getElementById("menu_options").style.visibility="hidden",document.getElementById("menu_options2").style.visibility="hidden",document.getElementById("menu_options3").style.visibility="hidden")}
function menu_visible_3(){document.getElementById("menu3").style.visibility="visible";document.getElementById("menu3").style.position="absolute";document.getElementById("menu3").style.left="95px";document.getElementById("menu1").style.visibility="hidden";document.getElementById("menu2").style.visibility="hidden";document.getElementById("menu4").style.visibility="hidden";document.getElementById("menu5").style.visibility="hidden";document.getElementById("menu6").style.visibility="hidden";document.getElementById("menu7").style.visibility=
"hidden";document.getElementById("menu8").style.visibility="hidden";document.getElementById("menu_options").style.visibility="hidden";document.getElementById("menu_options2").style.visibility="hidden";document.getElementById("menu_options3").style.visibility="hidden"}
function menu_visible_4(){2!=image_type1?(alert("The first image is not gray!"),menu_function1()):(document.getElementById("menu4").style.visibility="visible",document.getElementById("menu4").style.position="absolute",document.getElementById("menu4").style.left="95px",document.getElementById("menu1").style.visibility="hidden",document.getElementById("menu2").style.visibility="hidden",document.getElementById("menu3").style.visibility="hidden",document.getElementById("menu5").style.visibility="hidden",
document.getElementById("menu6").style.visibility="hidden",document.getElementById("menu7").style.visibility="hidden",document.getElementById("menu8").style.visibility="hidden",document.getElementById("menu_options").style.visibility="hidden",document.getElementById("menu_options2").style.visibility="hidden",document.getElementById("menu_options3").style.visibility="hidden")}
function menu_visible_5(){3!=image_type1?(alert("The first image is not color!"),menu_function1()):(document.getElementById("menu5").style.visibility="visible",document.getElementById("menu5").style.position="absolute",document.getElementById("menu5").style.left="95px",document.getElementById("menu1").style.visibility="hidden",document.getElementById("menu2").style.visibility="hidden",document.getElementById("menu3").style.visibility="hidden",document.getElementById("menu4").style.visibility="hidden",
document.getElementById("menu6").style.visibility="hidden",document.getElementById("menu7").style.visibility="hidden",document.getElementById("menu8").style.visibility="hidden",document.getElementById("menu_options").style.visibility="hidden",document.getElementById("menu_options2").style.visibility="hidden",document.getElementById("menu_options3").style.visibility="hidden")}
function menu_visible_6(){1!=image_type1?(alert("The first image is not binary!"),menu_function1()):(document.getElementById("menu6").style.visibility="visible",document.getElementById("menu6").style.position="absolute",document.getElementById("menu6").style.left="95px",document.getElementById("menu1").style.visibility="hidden",document.getElementById("menu2").style.visibility="hidden",document.getElementById("menu3").style.visibility="hidden",document.getElementById("menu4").style.visibility="hidden",
document.getElementById("menu5").style.visibility="hidden",document.getElementById("menu7").style.visibility="hidden",document.getElementById("menu8").style.visibility="hidden",document.getElementById("menu_options").style.visibility="hidden",document.getElementById("menu_options2").style.visibility="hidden",document.getElementById("menu_options3").style.visibility="hidden")}
function menu_visible_7(){2!=image_type1?(alert("The first image is not gray!"),menu_function1()):(document.getElementById("menu7").style.visibility="visible",document.getElementById("menu7").style.position="absolute",document.getElementById("menu7").style.left="95px",document.getElementById("menu1").style.visibility="hidden",document.getElementById("menu2").style.visibility="hidden",document.getElementById("menu3").style.visibility="hidden",document.getElementById("menu4").style.visibility="hidden",
document.getElementById("menu5").style.visibility="hidden",document.getElementById("menu6").style.visibility="hidden",document.getElementById("menu8").style.visibility="hidden",document.getElementById("menu_options").style.visibility="hidden",document.getElementById("menu_options2").style.visibility="hidden",document.getElementById("menu_options3").style.visibility="hidden")}
function menu_visible_8(){document.getElementById("menu8").style.visibility="visible";document.getElementById("menu8").style.position="absolute";document.getElementById("menu8").style.left="95px";document.getElementById("menu1").style.visibility="hidden";document.getElementById("menu2").style.visibility="hidden";document.getElementById("menu3").style.visibility="hidden";document.getElementById("menu4").style.visibility="hidden";document.getElementById("menu5").style.visibility="hidden";document.getElementById("menu6").style.visibility=
"hidden";document.getElementById("menu7").style.visibility="hidden";document.getElementById("menu_options").style.visibility="hidden";document.getElementById("menu_options2").style.visibility="hidden";document.getElementById("menu_options3").style.visibility="hidden"}
function menu_visible_options(){document.getElementById("menu_options").style.visibility="visible";document.getElementById("menu_options").style.position="absolute";document.getElementById("menu_options").style.left="95px";document.getElementById("menu1").style.visibility="hidden";document.getElementById("menu2").style.visibility="hidden";document.getElementById("menu3").style.visibility="hidden";document.getElementById("menu4").style.visibility="hidden";document.getElementById("menu5").style.visibility=
"hidden";document.getElementById("menu6").style.visibility="hidden";document.getElementById("menu7").style.visibility="hidden";document.getElementById("menu8").style.visibility="hidden";document.getElementById("menu_options2").style.visibility="hidden";document.getElementById("menu_options3").style.visibility="hidden"}
function menu_visible_options2(){document.getElementById("menu_options2").style.visibility="visible";document.getElementById("menu_options2").style.position="absolute";document.getElementById("menu_options2").style.left="95px";document.getElementById("menu1").style.visibility="hidden";document.getElementById("menu2").style.visibility="hidden";document.getElementById("menu3").style.visibility="hidden";document.getElementById("menu4").style.visibility="hidden";document.getElementById("menu5").style.visibility=
"hidden";document.getElementById("menu6").style.visibility="hidden";document.getElementById("menu7").style.visibility="hidden";document.getElementById("menu8").style.visibility="hidden";document.getElementById("menu_options").style.visibility="hidden";document.getElementById("menu_options3").style.visibility="hidden"}
function menu_visible_options3(){document.getElementById("menu_options3").style.visibility="visible";document.getElementById("menu_options3").style.position="absolute";document.getElementById("menu_options3").style.left="95px";document.getElementById("menu1").style.visibility="hidden";document.getElementById("menu2").style.visibility="hidden";document.getElementById("menu3").style.visibility="hidden";document.getElementById("menu4").style.visibility="hidden";document.getElementById("menu5").style.visibility=
"hidden";document.getElementById("menu6").style.visibility="hidden";document.getElementById("menu7").style.visibility="hidden";document.getElementById("menu8").style.visibility="hidden";document.getElementById("menu_options").style.visibility="hidden";document.getElementById("menu_options2").style.visibility="hidden"}
function menu_o1(){var c=0;for(i=0;1>i;){c=parseInt(prompt("Please enter the integer number (number >= 0, number <= 255):",""));if(1==Number.isNaN(c))return;null!=c&&Number.isInteger(c)&&0<=c&&255>=c?i++:alert("Wrong number.")}0>=document.getElementById("image1").width?alert("The first image is empty!"):sum(c,image1,null)}
function menu_o2(){0>=document.getElementById("image1").width?alert("The first image is empty!"):0>=document.getElementById("image2").width?alert("The second image is empty!"):2==image_type1&&2==image_type2||3==image_type1&&3==image_type2?sum(0,image1,image2):alert("Both images are of the same type!")}function menu_o21(){0>=document.getElementById("image1").width?alert("The first image is empty!"):average_filter(image1)}
function menu_o22(){0>=document.getElementById("image1").width?alert("The first image is empty!"):lp1_filter(image1)}function menu_o31(){0>=document.getElementById("image1").width?alert("The first image is empty!"):roberts_filter(image1)}function menu_o32(){0>=document.getElementById("image1").width?alert("The first image is empty!"):vertical_prewitt_filter(image1)}
function menu_12(){var c=0;for(i=0;1>i;){c=parseInt(prompt("Please enter the integer number (number > 0):",""));if(1==Number.isNaN(c))return;null!=c&&Number.isInteger(c)&&0<c?i++:alert("Wrong number.")}0>=document.getElementById("image1").width?alert("The first image is empty!"):pow(c,image1)}
function menu_13(){var c=0;for(i=0;1>i;){c=parseFloat(prompt("Please enter the float number (from 0 to 1):",""));if(1==Number.isNaN(c))return;null!=c&&0<c&&1>c?i++:alert("Wrong number.")}0>=document.getElementById("image1").width?alert("The first image is empty!"):pow(c,image1)}function menu_14(){0>=document.getElementById("image1").width?alert("The first image is empty!"):log(image1)}function menu_22(){menu_12()}function menu_23(){menu_13()}function menu_24(){menu_14()}
function menu_31(){var c=0,b=0;for(i=0;1>i;){c=parseInt(prompt("Please enter the integer number (x of vector):",""));if(1==Number.isNaN(c))return;null!=c&&Number.isInteger(c)?i++:alert("Wrong number.")}for(i=0;1>i;){b=parseInt(prompt("Please enter the integer number (y of vector):",""));if(1==Number.isNaN(b))return;null!=b&&Number.isInteger(b)?i++:alert("Wrong number.")}0>=document.getElementById("image1").width?alert("The first image is empty!"):move(c,b,image1)}
function menu_32(){var c=0,b=0,e=0,d=0;for(i=0;1>i;){c=parseInt(prompt("Please enter the integer number (x of point, number >= 0, number < width):",""));if(1==Number.isNaN(c))return;null!=c&&Number.isInteger(c)&&0<=c&&c<image1.width?i++:alert("Wrong number.")}for(i=0;1>i;){b=parseInt(prompt("Please enter the integer number (y of point, number >= 0, number < height):",""));if(1==Number.isNaN(b))return;null!=b&&Number.isInteger(b)&&0<=b&&b<image1.height?i++:alert("Wrong number.")}for(i=0;1>i;){e=parseInt(prompt("Please enter the integer number (x of vector):",
""));if(1==Number.isNaN(e))return;null!=e&&Number.isInteger(e)?i++:alert("Wrong number.")}for(i=0;1>i;){d=parseInt(prompt("Please enter the integer number (y of vector):",""));if(1==Number.isNaN(d))return;null!=d&&Number.isInteger(d)?i++:alert("Wrong number.")}0>=document.getElementById("image1").width?alert("The first image is empty!"):cut(c,b,e,d,image1)}
function menu_33(){var c=0,b=0,e=0,d=0,f=0,a=0;for(i=0;1>i;){c=parseInt(prompt("Please enter the integer number (x of first point, number >= 0, number < width):",""));if(1==Number.isNaN(c))return;null!=c&&Number.isInteger(c)&&0<=c&&c<image1.width?i++:alert("Wrong number.")}for(i=0;1>i;){b=parseInt(prompt("Please enter the integer number (y of first point, number >= 0, number < height):",""));if(1==Number.isNaN(b))return;null!=b&&Number.isInteger(b)&&0<=b&&b<image1.height?i++:alert("Wrong number.")}for(i=
0;1>i;){e=parseInt(prompt("Please enter the integer number (x of vector):",""));if(1==Number.isNaN(e))return;null!=e&&Number.isInteger(e)?i++:alert("Wrong number.")}for(i=0;1>i;){d=parseInt(prompt("Please enter the integer number (y of vector):",""));if(1==Number.isNaN(d))return;null!=d&&Number.isInteger(d)?i++:alert("Wrong number.")}for(i=0;1>i;){f=parseInt(prompt("Please enter the integer number (x of second point, number >= 0, number < width):",""));if(1==Number.isNaN(f))return;null!=f&&Number.isInteger(f)&&
0<=f&&f<image1.width?i++:alert("Wrong number.")}for(i=0;1>i;){a=parseInt(prompt("Please enter the integer number (y of second point, number >= 0, number < height):",""));if(1==Number.isNaN(a))return;null!=a&&Number.isInteger(a)&&0<=a&&a<image1.height?i++:alert("Wrong number.")}0>=document.getElementById("image1").width?alert("The first image is empty!"):copy2(c,b,e,d,f,a,image1)}var histogram1=0,histogram2=0,histogram1_end_ratio=1,histogram2_end_ratio=1;
function menu_41(){0>=document.getElementById("image1").width?alert("The first image is empty!"):(histogram2=histogram1=0,histogram(image1,image1_h,0,0,1,1),histogram(image1,image1_h,0,0,1,1))}
function menu_42(){var c=0,b=0;for(i=0;1>i;){c=parseInt(prompt("Please enter the integer number (x of move, number >= 0):",""));if(1==Number.isNaN(c))return;null!=c&&Number.isInteger(c)&&0<=c?i++:alert("Wrong number.")}for(i=0;1>i;){b=parseInt(prompt("Please enter the integer number (y of move, number >= 0):",""));if(1==Number.isNaN(b))return;null!=b&&Number.isInteger(b)&&0<=b?i++:alert("Wrong number.")}0>=document.getElementById("image1").width?alert("The first image is empty!"):(histogram1+=c,histogram2+=
b,histogram(image1,image1_h,histogram1,histogram2,1,1),histogram(image1,image1_h,histogram1,histogram2,1,1))}
function menu_43(){var c=0,b=0;for(i=0;1>i;){c=parseInt(prompt("Please enter the integer number (x of move, number >= 1):",""));if(1==Number.isNaN(c))return;null!=c&&Number.isInteger(c)&&1<=c?i++:alert("Wrong number.")}for(i=0;1>i;){b=parseInt(prompt("Please enter the integer number (y of move, number >= 1):",""));if(1==Number.isNaN(b))return;null!=b&&Number.isInteger(b)&&1<=b?i++:alert("Wrong number.")}0>=document.getElementById("image1").width?alert("The first image is empty!"):(histogram1_end_ratio=
c,histogram1_end_ratio2=b,histogram(image1,image1_h,histogram1,histogram2,histogram1_end_ratio,histogram1_end_ratio2),histogram(image1,image1_h,histogram1,histogram2,histogram1_end_ratio,histogram1_end_ratio2))}function menu_44(){0>=document.getElementById("image1").width?alert("The first image is empty!"):local_thresholding(image1)}function menu_51(){menu_41()}function menu_52(){menu_42()}function menu_53(){menu_43()}function menu_54(){menu_44()}
function menu_61(){0>=document.getElementById("image1").width?alert("The first image is empty!"):erosion(image1)}function menu_62(){0>=document.getElementById("image1").width?alert("The first image is empty!"):dilation(image1)}function menu_71(){menu_61()}function menu_72(){menu_62()}function menu_83(){0>=document.getElementById("image1").width?alert("The first image is empty!"):median_filter(image1)};function sum(c,b,e){show_button_normalization(!1);for(var d=0;d<b.width;d++)for(var f=0;f<b.height;f++){var a=get_pixel(d,f,b),h;null!=e?h=get_pixel(d,f,e):(h=Array(4),h[0]=c,h[1]=c,h[2]=c,h[3]=c);var g=Array(4);g[0]=parseInt(parseInt(.5*a[0])+parseInt(.5*h[0]));g[1]=parseInt(parseInt(.5*a[1])+parseInt(.5*h[1]));g[2]=parseInt(parseInt(.5*a[2])+parseInt(.5*h[2]));g[3]=parseInt(parseInt(.5*a[3])+parseInt(.5*h[3]));set_pixel(d,f,image1_a,g[0],g[1],g[2],g[3])}}
function pow(c,b){show_button_normalization(!1);for(var e=0;e<b.width;e++)for(var d=0;d<b.height;d++){var f=get_pixel(e,d,b);set_pixel(e,d,image1_a,Math.pow(f[0],c),Math.pow(f[1],c),Math.pow(f[2],c),f[3])}show_button_normalization(!0)}function log(c){show_button_normalization(!1);for(var b=0;b<c.width;b++)for(var e=0;e<c.height;e++){var d=get_pixel(b,e,c);set_pixel(b,e,image1_a,Math.log(d[0]),Math.log(d[1]),Math.log(d[2]),d[3])}show_button_normalization(!0)}
function normalization(c){show_button_normalization(!1);0>=c.width?alert("The image is empty!"):log(image1);for(var b=0,e=9999,d=0;d<c.width;d++)for(var f=0;f<c.height;f++){var a=get_pixel(d,f,c);a[0]>b&&(b=a[0]);a[1]>b&&(b=a[1]);a[2]>b&&(b=a[2]);a[0]<e&&(e=a[0]);a[1]<e&&(e=a[1]);a[2]<e&&(e=a[2])}for(d=0;d<c.width;d++)for(f=0;f<c.height;f++)a=get_pixel(d,f,c),a[0]=parseInt(255*(a[0]-e)/(b-e)),a[1]=parseInt(255*(a[1]-e)/(b-e)),a[2]=parseInt(255*(a[2]-e)/(b-e)),set_pixel(d,f,c,a[0],a[1],a[2],a[3])}
function move(c,b,e){show_button_normalization(!1);for(var d=0;d<e.width;d++)for(var f=0;f<e.height;f++)set_pixel(d,f,image1_a,255,255,255,255);for(d=0;d<e.width;d++)for(f=0;f<e.height;f++){var a=get_pixel(d,f,e);set_pixel(d+c,f+b,image1_a,a[0],a[1],a[2],a[3])}if(0<c)for(d=0;d<c;d++)for(f=0;f<e.height;f++)set_pixel(d,f,image1_a,255,255,255,255);else for(d=0;d<-1*c;d++)for(f=0;f<e.height;f++)set_pixel(e.height-d-1,f,image1_a,255,255,255,255);if(0<b)for(d=0;d<e.width;d++)for(f=0;f<b;f++)set_pixel(d,
f,image1_a,255,255,255,255);else for(d=0;d<e.width;d++)for(f=0;f<-1*b;f++)set_pixel(d,e.width-f-1,image1_a,255,255,255,255)}
function cut(c,b,e,d,f){show_button_normalization(!1);move(-1*c,-1*b,image1);if(0>=f.height-e)for(c=0;c<-1*(f.height-e);c++)for(b=0;b<f.height;b++)set_pixel(c,b,image1_a,255,255,255,255);else for(c=0;c<f.height-e;c++)for(b=0;b<f.height;b++)set_pixel(f.height-1-c,b,image1_a,255,255,255,255);if(0>=f.width-d)for(c=0;c<f.width;c++)for(b=0;b<-1*(f.width-d);b++)set_pixel(c,b,image1_a,255,255,255,255);else for(c=0;c<f.width;c++)for(b=0;b<f.width-d;b++)set_pixel(c,f.width-1-b,image1_a,255,255,255,255)}
function copy2(c,b,e,d,f,a,h){show_button_normalization(!1);cut(c,b,e,d,h);for(c=0;c<e;c++)for(b=0;b<d;b++){var g=get_pixel(c,b,image1_a);set_pixel(c+f,b+a,image1_a,g[0],g[1],g[2],g[3])}for(c=0;c<h.width;c++)for(b=0;b<a;b++)g=get_pixel(c,b,image1),set_pixel(c,b,image1_a,g[0],g[1],g[2],g[3]);for(c=0;c<h.width;c++)for(b=0;b<h.height;b++)g=get_pixel(c,b,image1),set_pixel(c,b,image1_a,g[0],g[1],g[2],g[3]);for(c=0;c<f;c++)for(b=0;b<h.height;b++)g=get_pixel(c,b,image1),set_pixel(c,b,image1_a,g[0],g[1],
g[2],g[3]);for(c=0;c<h.width;c++)for(b=0;b<h.height;b++)g=get_pixel(c,b,image1),set_pixel(c,b,image1_a,g[0],g[1],g[2],g[3])}
function histogram(c,b,e,d,f,a){b.getContext("2d").clearRect(0,0,b.height,b.width);for(var h=c.getContext("2d").getImageData(0,0,c.height,c.width),g=Array(255),l=Array(255),m=Array(255),k=0;256>k;k++)g[k]=0,l[k]=0,m[k]=0;for(k=0;k<c.width;k++)for(var n=0;n<c.height;n++)index=4*(k*c.height+n),g[h.data[index+0]]++,l[h.data[index+1]]++,m[h.data[index+2]]++;for(k=c=0;256>k;k++)c<g[k]&&(c=g[k]),c<l[k]&&(c=l[k]),c<m[k]&&(c=m[k]);b=b.getContext("2d");b.font="10pt Arial";b.fillStyle="black";b.textBaseline=
"top";b.textAlign="center";b.font="8pt Arial";b.fillText(parseInt(d)*parseInt(f),8,120);b.fillText(parseInt(parseInt(c)+parseInt(d))*parseInt(f),8,20);b.fillText(parseInt(e)*parseInt(a),25,160);b.fillText(parseInt(255+parseInt(e))*parseInt(a),265,160);b.moveTo(20,150);b.lineTo(20,0);b.lineTo(17,5);b.lineTo(20,0);b.lineTo(23,5);b.stroke();b.moveTo(20,150);b.moveTo(20,150);b.lineTo(280,150);b.lineTo(275,153);b.lineTo(280,150);b.lineTo(275,147);b.stroke();b.strokeStyle="rgba(255,0,0,0.33)";b.beginPath();
b.moveTo(20,150);for(k=0;256>k;k++)b.lineTo(20+k,150-130*g[k]/c);b.stroke();b.strokeStyle="rgba(0,255,0,0.33)";b.beginPath();b.moveTo(20,150);for(k=0;256>k;k++)b.lineTo(20+k,150-130*l[k]/c);b.stroke();b.strokeStyle="rgba(0,0,255,0.33)";b.beginPath();b.moveTo(20,150);for(k=0;256>k;k++)b.lineTo(20+k,150-130*m[k]/c);b.stroke()}
function local_thresholding(c){for(var b=0;b<c.width;b++)for(var e=0;e<c.height;e++){var d=[255,255,255],f=[0,0,0],a;0<=b-1&&(0<=e-1&&(a=get_pixel(b-1,e-1,c),a[0]>f[0]&&(f[0]=a[0]),a[1]>f[1]&&(f[1]=a[1]),a[2]>f[2]&&(f[2]=a[2]),a[0]<d[0]&&(d[0]=a[0]),a[1]<d[1]&&(d[1]=a[1]),a[2]<d[2]&&(d[2]=a[2])),a=get_pixel(b-1,e,c),a[0]>f[0]&&(f[0]=a[0]),a[1]>f[1]&&(f[1]=a[1]),a[2]>f[2]&&(f[2]=a[2]),a[0]<d[0]&&(d[0]=a[0]),a[1]<d[1]&&(d[1]=a[1]),a[2]<d[2]&&(d[2]=a[2]),e<c.width&&(a=get_pixel(b-1,e+1,c),a[0]>f[0]&&
(f[0]=a[0]),a[1]>f[1]&&(f[1]=a[1]),a[2]>f[2]&&(f[2]=a[2]),a[0]<d[0]&&(d[0]=a[0]),a[1]<d[1]&&(d[1]=a[1]),a[2]<d[2]&&(d[2]=a[2])));0<=e-1&&(a=get_pixel(b,e-1,c),a[0]>f[0]&&(f[0]=a[0]),a[1]>f[1]&&(f[1]=a[1]),a[2]>f[2]&&(f[2]=a[2]),a[0]<d[0]&&(d[0]=a[0]),a[1]<d[1]&&(d[1]=a[1]),a[2]<d[2]&&(d[2]=a[2]));a=get_pixel(b,e,c);a[0]>f[0]&&(f[0]=a[0]);a[1]>f[1]&&(f[1]=a[1]);a[2]>f[2]&&(f[2]=a[2]);a[0]<d[0]&&(d[0]=a[0]);a[1]<d[1]&&(d[1]=a[1]);a[2]<d[2]&&(d[2]=a[2]);e<c.height&&(a=get_pixel(b,e+1,c),a[0]>f[0]&&(f[0]=
a[0]),a[1]>f[1]&&(f[1]=a[1]),a[2]>f[2]&&(f[2]=a[2]),a[0]<d[0]&&(d[0]=a[0]),a[1]<d[1]&&(d[1]=a[1]),a[2]<d[2]&&(d[2]=a[2]));b+1<c.width&&(0<=e-1&&(a=get_pixel(b+1,e-1,c),a[0]>f[0]&&(f[0]=a[0]),a[1]>f[1]&&(f[1]=a[1]),a[2]>f[2]&&(f[2]=a[2]),a[0]<d[0]&&(d[0]=a[0]),a[1]<d[1]&&(d[1]=a[1]),a[2]<d[2]&&(d[2]=a[2])),a=get_pixel(b+1,e,c),a[0]>f[0]&&(f[0]=a[0]),a[1]>f[1]&&(f[1]=a[1]),a[2]>f[2]&&(f[2]=a[2]),a[0]<d[0]&&(d[0]=a[0]),a[1]<d[1]&&(d[1]=a[1]),a[2]<d[2]&&(d[2]=a[2]),e<c.height&&(a=get_pixel(b+1,e+1,c),
a[0]>f[0]&&(f[0]=a[0]),a[1]>f[1]&&(f[1]=a[1]),a[2]>f[2]&&(f[2]=a[2]),a[0]<d[0]&&(d[0]=a[0]),a[1]<d[1]&&(d[1]=a[1]),a[2]<d[2]&&(d[2]=a[2])));a=get_pixel(b,e,c);a[0]=a[0]>(d[0]+f[0])/2?255:0;a[1]=a[1]>(d[1]+f[1])/2?255:0;a[2]=a[2]>(d[2]+f[2])/2?255:0;set_pixel(b,e,image1_a,a[0],a[1],a[2],a[3])}}
function erosion(c){for(var b=0;b<c.width;b++)for(var e=0;e<c.height;e++){var d=[255,255,255],f=[0,0,0],a,h=get_pixel(b,e,c);0<=b-1&&(0<=e-1&&(a=get_pixel(b-1,e-1,c),a[0]>f[0]&&(f[0]=a[0]),a[1]>f[1]&&(f[1]=a[1]),a[2]>f[2]&&(f[2]=a[2]),a[0]<d[0]&&(d[0]=a[0]),a[1]<d[1]&&(d[1]=a[1]),a[2]<d[2]&&(d[2]=a[2])),a=get_pixel(b-1,e,c),a[0]>f[0]&&(f[0]=a[0]),a[1]>f[1]&&(f[1]=a[1]),a[2]>f[2]&&(f[2]=a[2]),a[0]<d[0]&&(d[0]=a[0]),a[1]<d[1]&&(d[1]=a[1]),a[2]<d[2]&&(d[2]=a[2]),e<c.height&&(a=get_pixel(b-1,e+1,c),a[0]>
f[0]&&(f[0]=a[0]),a[1]>f[1]&&(f[1]=a[1]),a[2]>f[2]&&(f[2]=a[2]),a[0]<d[0]&&(d[0]=a[0]),a[1]<d[1]&&(d[1]=a[1]),a[2]<d[2]&&(d[2]=a[2])));0<=e-1&&(a=get_pixel(b,e-1,c),a[0]>f[0]&&(f[0]=a[0]),a[1]>f[1]&&(f[1]=a[1]),a[2]>f[2]&&(f[2]=a[2]),a[0]<d[0]&&(d[0]=a[0]),a[1]<d[1]&&(d[1]=a[1]),a[2]<d[2]&&(d[2]=a[2]));a=get_pixel(b,e,c);a[0]>f[0]&&(f[0]=a[0]);a[1]>f[1]&&(f[1]=a[1]);a[2]>f[2]&&(f[2]=a[2]);a[0]<d[0]&&(d[0]=a[0]);a[1]<d[1]&&(d[1]=a[1]);a[2]<d[2]&&(d[2]=a[2]);e<c.height&&(a=get_pixel(b,e+1,c),a[0]>f[0]&&
(f[0]=a[0]),a[1]>f[1]&&(f[1]=a[1]),a[2]>f[2]&&(f[2]=a[2]),a[0]<d[0]&&(d[0]=a[0]),a[1]<d[1]&&(d[1]=a[1]),a[2]<d[2]&&(d[2]=a[2]));b+1<c.width&&(0<=e-1&&(a=get_pixel(b+1,e-1,c),a[0]>f[0]&&(f[0]=a[0]),a[1]>f[1]&&(f[1]=a[1]),a[2]>f[2]&&(f[2]=a[2]),a[0]<d[0]&&(d[0]=a[0]),a[1]<d[1]&&(d[1]=a[1]),a[2]<d[2]&&(d[2]=a[2])),a=get_pixel(b+1,e,c),a[0]>f[0]&&(f[0]=a[0]),a[1]>f[1]&&(f[1]=a[1]),a[2]>f[2]&&(f[2]=a[2]),a[0]<d[0]&&(d[0]=a[0]),a[1]<d[1]&&(d[1]=a[1]),a[2]<d[2]&&(d[2]=a[2]),e<c.height&&(a=get_pixel(b+1,
e+1,c),a[0]>f[0]&&(f[0]=a[0]),a[1]>f[1]&&(f[1]=a[1]),a[2]>f[2]&&(f[2]=a[2]),a[0]<d[0]&&(d[0]=a[0]),a[1]<d[1]&&(d[1]=a[1]),a[2]<d[2]&&(d[2]=a[2])));set_pixel(b,e,image1_a,d[0],d[1],d[2],h[3])}}
function dilation(c){for(var b=0;b<c.width;b++)for(var e=0;e<c.height;e++){var d=255,f=0,a,h=get_pixel(b,e,c);0<=b-1&&(0<=e-1&&(a=get_pixel(b-1,e-1,c),(a[0]+a[1]+a[2])/3>f?f=(a[0]+a[1]+a[2])/3:(a[0]+a[1]+a[2])/3<d&&(d=(a[0]+a[1]+a[2])/3)),a=get_pixel(b-1,e,c),(a[0]+a[1]+a[2])/3>f?f=(a[0]+a[1]+a[2])/3:(a[0]+a[1]+a[2])/3<d&&(d=(a[0]+a[1]+a[2])/3),e<c.height&&(a=get_pixel(b-1,e+1,c),(a[0]+a[1]+a[2])/3>f?f=(a[0]+a[1]+a[2])/3:(a[0]+a[1]+a[2])/3<d&&(d=(a[0]+a[1]+a[2])/3)));0<=e-1&&(a=get_pixel(b,e-1,c),
(a[0]+a[1]+a[2])/3>f?f=(a[0]+a[1]+a[2])/3:(a[0]+a[1]+a[2])/3<d&&(d=(a[0]+a[1]+a[2])/3));a=get_pixel(b,e,c);(a[0]+a[1]+a[2])/3>f?f=(a[0]+a[1]+a[2])/3:(a[0]+a[1]+a[2])/3<d&&(d=(a[0]+a[1]+a[2])/3);e<c.height&&(a=get_pixel(b,e+1,c),(a[0]+a[1]+a[2])/3>f?f=(a[0]+a[1]+a[2])/3:(a[0]+a[1]+a[2])/3<d&&(d=(a[0]+a[1]+a[2])/3));b+1<c.width&&(0<=e-1&&(a=get_pixel(b+1,e-1,c),(a[0]+a[1]+a[2])/3>f?f=(a[0]+a[1]+a[2])/3:(a[0]+a[1]+a[2])/3<d&&(d=(a[0]+a[1]+a[2])/3)),a=get_pixel(b+1,e,c),(a[0]+a[1]+a[2])/3>f&&(f=(a[0]+
a[1]+a[2])/3),e<c.height&&(a=get_pixel(b+1,e+1,c),(a[0]+a[1]+a[2])/3>f&&(f=(a[0]+a[1]+a[2])/3)));set_pixel(b,e,image1_a,f,f,f,h[3])}}
function median_filter(c){for(var b=0;b<c.width;b++)for(var e=0;e<c.height;e++){var d,f=[],a=[],h=[],g=0,l=get_pixel(b,e,c);0<=b-1&&(0<=e-1&&(d=get_pixel(b-1,e-1,c),f[g]=d[0],a[g]=d[1],h[g]=d[2],g++),d=get_pixel(b-1,e,c),f[g]=d[0],a[g]=d[1],h[g]=d[2],g++,e<c.height&&(d=get_pixel(b-1,e+1,c),f[g]=d[0],a[g]=d[1],h[g]=d[2],g++));0<=e-1&&(d=get_pixel(b,e-1,c),f[g]=d[0],a[g]=d[1],h[g]=d[2],g++);d=get_pixel(b,e,c);f[g]=d[0];a[g]=d[1];h[g]=d[2];g++;e<c.height&&(d=get_pixel(b,e+1,c),f[g]=d[0],a[g]=d[1],h[g]=
d[2],g++);b+1<c.width&&(0<=e-1&&(d=get_pixel(b+1,e-1,c),f[g]=d[0],a[g]=d[1],h[g]=d[2],g++),d=get_pixel(b+1,e,c),f[g]=d[0],a[g]=d[1],h[g]=d[2],g++,e<c.height&&(d=get_pixel(b+1,e+1,c),f[g]=d[0],a[g]=d[1],h[g]=d[2],g++));f.sort();a.sort();h.sort();1==g%2?set_pixel(b,e,image1_a,f[Math.floor(g/2)],a[Math.floor(g/2)],h[Math.floor(g/2)],l[3]):set_pixel(b,e,image1_a,(f[g/2]+f[g/2-1])/2,(a[g/2]+a[g/2-1])/2,(h[g/2]+h[g/2-1])/2,l[3])}}
function roberts_filter(c){for(var b=0;b<c.width;b++)for(var e=0;e<c.height;e++){var d=get_pixel(b,e,c),f=get_pixel(b+1,e+1,c);d[0]-=f[0];d[1]-=f[1];d[2]-=f[2];d[0]=Math.abs(d[0]);d[1]=Math.abs(d[1]);d[2]=Math.abs(d[2]);var f=get_pixel(b+1,e,c),a=get_pixel(b,e+1,c);f[0]-=a[0];f[1]-=a[1];f[2]-=a[2];f[0]=Math.abs(f[0]);f[1]=Math.abs(f[1]);f[2]=Math.abs(f[2]);a[0]=d[0]+f[0];a[1]=d[1]+f[1];a[2]=d[2]+f[2];d=get_pixel(b,e,c);set_pixel(b,e,image1_a,a[0],a[1],a[2],d[3])}}
function average_filter(c){for(var b=0;b<c.width;b++)for(var e=0;e<c.height;e++){var d,f=0,a=0,h=0,g=0,l=get_pixel(b,e,c);0<=b-1&&(0<=e-1&&(d=get_pixel(b-1,e-1,c),a+=d[0],h+=d[1],g+=d[2],f++),d=get_pixel(b-1,e,c),a+=d[0],h+=d[1],g+=d[2],f++,e<c.height&&(d=get_pixel(b-1,e+1,c),a+=d[0],h+=d[1],g+=d[2],f++));0<=e-1&&(d=get_pixel(b,e-1,c),a+=d[0],h+=d[1],g+=d[2],f++);d=get_pixel(b,e,c);a+=d[0];h+=d[1];g+=d[2];f++;e<c.height&&(d=get_pixel(b,e+1,c),a+=d[0],h+=d[1],g+=d[2],f++);b+1<c.width&&(0<=e-1&&(d=
get_pixel(b+1,e-1,c),a+=d[0],h+=d[1],g+=d[2],f++),d=get_pixel(b+1,e,c),a+=d[0],h+=d[1],g+=d[2],f++,e<c.height&&(d=get_pixel(b+1,e+1,c),a+=d[0],h+=d[1],g+=d[2],f++));a/=f;h/=f;g/=f;0<=b-1&&(0<=e-1&&set_pixel(b-1,e-1,image1_a,a,h,g,l[3]),set_pixel(b-1,e,image1_a,a,h,g,l[3]),e<c.height&&set_pixel(b-1,e+1,image1_a,a,h,g,l[3]));0<=e-1&&set_pixel(b,e-1,image1_a,a,h,g,l[3]);set_pixel(b,e,image1_a,a,h,g,l[3]);e<c.height&&set_pixel(b,e+1,image1_a,a,h,g,l[3]);b+1<c.width&&(0<=e-1&&set_pixel(b+1,e-1,image1_a,
a,h,g,l[3]),set_pixel(b+1,e,image1_a,a,h,g,l[3]),e<c.height&&set_pixel(b+1,e+1,image1_a,a,h,g,l[3]))}}
function lp1_filter(c){for(var b=0;b<c.width;b++)for(var e=0;e<c.height;e++){var d,f=0,a=0,h=0,g=0,l=get_pixel(b,e,c);0<=b-1&&(0<=e-1&&(d=get_pixel(b-1,e-1,c),a+=d[0],h+=d[1],g+=d[2],f++),d=get_pixel(b-1,e,c),a+=d[0],h+=d[1],g+=d[2],f++,e<c.height&&(d=get_pixel(b-1,e+1,c),a+=d[0],h+=d[1],g+=d[2],f++));0<=e-1&&(d=get_pixel(b,e-1,c),a+=d[0],h+=d[1],g+=d[2],f++);d=get_pixel(b,e,c);a+=d[0];h+=d[1];g+=d[2];a+=d[0];h+=d[1];g+=d[2];f++;f++;e<c.height&&(d=get_pixel(b,e+1,c),a+=d[0],h+=d[1],g+=d[2],f++);b+
1<c.width&&(0<=e-1&&(d=get_pixel(b+1,e-1,c),a+=d[0],h+=d[1],g+=d[2],f++),d=get_pixel(b+1,e,c),a+=d[0],h+=d[1],g+=d[2],f++,e<c.height&&(d=get_pixel(b+1,e+1,c),a+=d[0],h+=d[1],g+=d[2],f++));a/=f;h/=f;g/=f;0<=b-1&&(0<=e-1&&set_pixel(b-1,e-1,image1_a,a,h,g,l[3]),set_pixel(b-1,e,image1_a,a,h,g,l[3]),e<c.height&&set_pixel(b-1,e+1,image1_a,a,h,g,l[3]));0<=e-1&&set_pixel(b,e-1,image1_a,a,h,g,l[3]);set_pixel(b,e,image1_a,a,h,g,l[3]);e<c.height&&set_pixel(b,e+1,image1_a,a,h,g,l[3]);b+1<c.width&&(0<=e-1&&set_pixel(b+
1,e-1,image1_a,a,h,g,l[3]),set_pixel(b+1,e,image1_a,a,h,g,l[3]),e<c.height&&set_pixel(b+1,e+1,image1_a,a,h,g,l[3]))}}
function vertical_prewitt_filter(c){for(var b=0;b<c.width;b++)for(var e=0;e<c.height;e++){var d,f=0,a=0,h=0,g=get_pixel(b,e,c);0<=b-1&&(0<=e-1&&(d=get_pixel(b-1,e-1,c),f+=d[0],a+=d[1],h+=d[2]),d=get_pixel(b-1,e,c),f+=d[0],a+=d[1],h+=d[2],e<c.height&&(d=get_pixel(b-1,e+1,c),f+=d[0],a+=d[1],h+=d[2]));b+1<c.width&&(0<=e-1&&(d=get_pixel(b+1,e-1,c),f-=d[0],a-=d[1],h-=d[2]),d=get_pixel(b+1,e,c),f-=d[0],a-=d[1],h-=d[2],e<c.height&&(d=get_pixel(b+1,e+1,c),f-=d[0],a-=d[1],h-=d[2]));set_pixel(b,e,image1_a,
f,a,h,g[3])}};var image_type1=-1,image_type2=-1;function clear_file1(){document.getElementById("file1").value="";image_type1=-1;image1.width=0;image1.height=0;image1_a.width=0;image1_a.height=0;image1_h.width=280;image1_h.height=170;image1_h.getContext("2d").clearRect(0,0,image1_h.width,image1_h.height);show_button_normalization(!1)}function clear_file2(){document.getElementById("file2").value="";image_type2=-1;image2.width=0;image2.height=0}
function draw_image(c,b){var e=new window.Image;e.addEventListener("load",function(){b.getContext("2d").drawImage(e,0,0)});e.setAttribute("src",c);b.width=e.width;b.height=e.height}
document.getElementById("file1").onchange=function(){var c=document.getElementById("file1").value;"p"!=c[c.length-3]||"n"!=c[c.length-2]||"g"!=c[c.length-1]?alert("The first image is not PNG!"):(draw_image("png_images/"+document.getElementById("file1").value,image1),draw_image("png_images/"+document.getElementById("file1").value,image1_a))};
document.getElementById("file2").onchange=function(){var c=document.getElementById("file2").value;"p"!=c[c.length-3]||"n"!=c[c.length-2]||"g"!=c[c.length-1]?alert("The first image is not PNG!"):draw_image("png_images/"+document.getElementById("file2").value,image2)};
document.addEventListener("DOMContentLoaded",function(){clear_file1();clear_file2();show_button_normalization(!1);document.getElementById("menu1").style.visibility="hidden";document.getElementById("menu2").style.visibility="hidden";document.getElementById("menu3").style.visibility="hidden";document.getElementById("menu4").style.visibility="hidden";document.getElementById("menu5").style.visibility="hidden";document.getElementById("menu6").style.visibility="hidden";document.getElementById("menu7").style.visibility=
"hidden";document.getElementById("menu8").style.visibility="hidden";document.getElementById("menu_options").style.visibility="hidden";document.getElementById("menu_options2").style.visibility="hidden";document.getElementById("menu_options3").style.visibility="hidden"});function show_button_normalization(c){1==c?document.getElementById("button_normalize1").style.visibility="visible":document.getElementById("button_normalize1").style.visibility="hidden"}
function image_type(c){var b=1,e=1;if(0>=c.height||0>=c.width)return-1;for(var d=0;d<c.height;d++)for(var f=0;f<c.width;f++){var a=get_pixel(d,f,c);if(0!=a[0]&&255!=a[0]||0!=a[1]&&255!=a[1]||0!=a[2]&&255!=a[2])b=0;if(a[0]!=a[1]||a[1]!=a[2])e=0}return 1==b?1:1==e?2:3};
